FROM oven/bun:1.1-alpine AS base
WORKDIR /app

ARG WORKER=messaging

COPY package.json bun.lockb* ./
RUN bun install --frozen-lockfile --production

COPY . .

CMD ["sh", "-c", "bun src/workers/${WORKER}.worker.ts"]
