FROM oven/bun:1.1-alpine AS base
WORKDIR /app

ARG WORKER=messaging

COPY package.json bun.lock* ./
RUN bun install --frozen-lockfile --production

COPY . .

ENV WORKER_NAME=${WORKER}

CMD ["sh", "-c", "bun src/workers/${WORKER_NAME}.worker.ts"]
